describe('Los estudiantes login', function() {
    it('Visits los estudiantes and fails at login', function() {
        cy.visit('https://losestudiantes.co')
        cy.contains('Cerrar').click()
        cy.wait(3000)
        cy.screenshot('1_Inicio')
        cy.contains('Ingresar').click()
        cy.get('.cajaLogIn').find('input[name="correo"]').click().type("prueba@example.com")
        cy.get('.cajaLogIn').find('input[name="password"]').click().type("12345678")
        cy.wait(3000)
        cy.screenshot('2_Login')
        cy.get('.cajaLogIn').click().contains('Ingresar').click()
        cy.contains('Los Estudiantes')
            //cy.contains('Salir').click()
        cy.get('#cuenta').click()
        cy.wait(3000)
        cy.screenshot('3_home_estudiante')
        cy.contains('Salir').click()
        cy.wait(3000)
        cy.screenshot('4_salir')
        cy.contains('Ingresar')
    })
})